### ISSUE TITLE
Disable headerHash?

### ISSUE THREAD

**Issue by impartdan** [d4nyll/smartscroll#25]
Is it possible to not use the headerHash?

**Comment by karneaud** [comment]
+1

**Comment by karneaud** [comment]
Do you get any "jumpy" behaviour when using it?

**Comment by d4nyll** [comment]
I considered this while writing the library 2 years ago, but because `#` means 'go to the top of the page', so if you use hash values you should specify the `headerHash` otherwise it would jump a bit.

`headerHash` - (String) The hash for the section above the sections, must be non-empty to reliably ensure the page do not jump when updating the hash value across browsers (as # means _top)

If you have any ideas on how to mitigate this issue please comment here!
